apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: appnova
  namespace: palmeiras
spec:
  interval: 10m0s
  path: ./clusters/rafael/apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
