apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-metabase
  labels:
    app: mysql-metabase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-metabase
  template:
    metadata:
      labels:
        app: mysql-metabase
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          args:
            - "--default-authentication-plugin=mysql_native_password"
          ports:
            - containerPort: 3306
              name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_PASSWORD
          # sem volume => ephemeral
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 15
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-metabase
  labels:
    app: mysql-metabase
spec:
  selector:
    app: mysql-metabase
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  type: ClusterIP
