apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "rootpass-change"
  MYSQL_DATABASE: "metabaseappdb"
  MYSQL_USER: "metabase"
  MYSQL_PASSWORD: "metabasepass-change"
